---
title: "The Causal Impact of Romneycare on Massachusetts' Mortality Rate using Synthetic Control"
author: "Elle Boodsakorn, Parker Gauthier, Amal Kadri, Alice Kemp and Austin Longoria"
date: 'University of Texas at Austin - ECO395M - Spring 2022'
output: pdf_document
---

# Abstract

\newpage

# Introduction
  Access to healthcare through affordable health insurance remains one of the most divisive policy debates in the United States, with critics of a privatized system arguing in favor of a widespread, easily accessible option targeted at low income households to increase the quality and quantity of health care. However, some supporters of private insurance argue against such a system, stating that insurance provided by the federal government unfairly burdens taxpayers, many of whom opt for private coverage through their employers. Before the groundbreaking introduction of the Affordable Care Act in 2008, better known as "Obamacare", the state of Massachusetts passed its own state-provided health insurance program signed into law by Senator Mitt Romney in 2006. The program, dubbed "Romneycare" and the first of its kind in the U.S., provided free and heavily subsidized health insurance to the lowest income resident of the state, and mandated that nearly all residents obtain a minimal level of coverage. To aid in the provision of coverage to higher earners, the law also required every employer in the state with over ten full-time employees to provide a health insurance plan to workers. Before the program was heavily rolled back in favor of Obamacare in 2012, over 97% of Massachusetts residents had health insurance coverage (**cite - brookings**). Many studies have investigated the effects of Romneycare and Obamacare on statistics such as health coverage, insurance utilization, and health care pricing, however, few have attempted to isolate the causal effect of mandated affordable health coverage on mortality rates. One of the reasons why this effect can be difficult to identify is due to the distribution of health care in the U.S. - as insurance is not randomly assigned to individuals but normally obtained through employers, low income individuals tend to have minimal coverage, if at all and sub-optimal quality of care. As a result, worse health outcomes tend to be correlated with individuals on the lower end of the socioeconomic spectrum, making any causal analysis particularly complex. However, using causal inference techniques such as Synthetic Control, we will be able to isolate the direct effect of Romneycare on mortality outcomes. Overall, we theorize that the nearly maximized population of residents with mandated health insurance coverage required by Romneycare will decrease mortality due to more individuals seeking both preventative and emergency care without the burden of uninsured pricing. 

# Previous Literature
In this report, we will attempt to replicate Sommers, Long and Baicker's 2014 study of changes in Massachusetts' mortality after the introduction of Romneycare and the Massachusetts Health Care Reform. In their analysis, the authors utilized a natural experiment by comparing population-level Massachusetts mortality obtained from the Center for Disease Control (CDC) following the implementation of Romneycare to counties covering approximately 25% of the United States. The counties included were selected to best match the racial makeup, gender balance, age cohorts, and baseline death rates found in Massachusetts. Using a propensity score framework, the authors 

The results, published in the American College of Physicians' Annals of Internal Medicine, found an overall annual decrease of 320 deaths per year in Massachusetts as compared to counties outside the state. 

# Data

# Methodology

Let $Y_{it}$ be the mortality rate for state $i$ at time period $t$ and let $D_i \in (0,1)$ denote the binary treatment indicator of state $i$. Our goal is to estimate the average treatment effect of introducing Romneycare on mortality rates in Massachusetts, or: 
$$ATT_t = E[Y_{it}^1 - Y_{it}^0 | D_i = 1] = E[Y_{it}^1|D_i = 1] - E[Y_{it}^0|D_i = 1]$$
In words, the ATT can be calculated as the estimate of the difference in outcomes for the treated units in the world where they were treated versus the world where they were not treated. The key crux to this calculation lies in our ability to measure $Y_{it}^0|D_i=1$, or how the treated units would have performed had they not been treated. This is where the idea of Synthetic Control comes into play. The Synthetic Control estimator interpolates this unknown by using a weighted average of the untreated units to create a synthetic untreated unit with pre-treatment characteristics similar to those of the treated unit. In our analysis, we will use cross-sectional time-series mortality data from counties outside of Massachusetts that did not have affordable care laws that most closely match the demographic makeup of Massachusetts. Using SC, an optimized weighted average of these selected counties' mortality rates will serve as our untreated unit to compare to Massachusetts both before and after Romneycare was enacted. 

# Analysis

# Conclusion